<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Post extends BasePost
{
	public function fetchAll()
	{
		return Doctrine::getTable('Post')->findAll();
	}
	
	public function fetchOne($id)
	{
		return Doctrine::getTable('Post')->find($id);
	}
}